root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"

  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "node_modules", ".git"]
  exclude_file = ["docs/docs.go"]
  delay = 500

[log]
  time = true